version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:15
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    ports:
      - '3000:3000'
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: product-service
    environment:
      - DB_HOST=postgres
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: order-service
    environment:
      - DB_HOST=postgres
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: payment-service
    environment:
      - DB_HOST=postgres
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: notification-service
    environment:
      - DB_HOST=postgres
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq

volumes:
  rabbitmq_data:
  postgres_data:
